; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.1.4-LPC-5 on Thu Oct 22 2020 21:31:39 GMT+0200 (CEST)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


