; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.1.4-LPC-5 on Thu Oct 22 2020 21:31:39 GMT+0200 (CEST)
; Wait for set temperatures to be reached
M116 P0

