; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.2.1-LPC+17 on Fri Jul 09 2021 17:49:18 GMT+0200 (heure d’été d’Europe centrale)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


