; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.2.1-LPC+17 on Fri Jul 09 2021 17:49:18 GMT+0200 (heure d’été d’Europe centrale)
M280 P0 S90 ; retract BLTouch

