; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.2.1-LPC+17 on Fri Jul 09 2021 17:49:20 GMT+0200 (heure d’été d’Europe centrale)
; Wait for set temperatures to be reached
M116 P0

